#!/bin/bash
### BY ALFAINTERNET ###
rm -f install
rm -f Plus
rm -f install*
rm -f Plus*
clear
echo -e "\033[1;33mBAIXANDO, INSTALADOR \033[0m"
sleep 3s
wget https://raw.githubusercontent.com/modderajuda/websocketsecurity/main/F2/Plus > /dev/null 2>&1
echo ""
echo -e "\033[1;33mBAIXADO !"
sleep 3s
echo ""
echo -e "\033[1;33mINICIANDO, INSTALADOR \033[0m"
sleep 5s
chmod 777 Plus && ./Plus
rm -f Plus*
clear
echo ""
echo -e "\033[1;33mINICIANDO, INSTALADOR \033[0m"
sleep 5s
 ### "APT INSTALL"
echo ""
echo -e "\033[1;33mBAIXANDO, PACOTES EXTRAS \033[0m"
sleep 3s
apt-get install screen -y > /dev/null 2>&1
apt-get install htop -y > /dev/null 2>&1
apt-get install iptables -y > /dev/null 2>&1
apt-get install net-tools -y > /dev/null 2>&1
apt-get install sysstat -y > /dev/null 2>&1
apt-get install slurm -y > /dev/null 2>&1
apt-get install intel-microcode -y > /dev/null 2>&1
apt-get install haveged -y > /dev/null 2>&1
apt-get install ethtool -y > /dev/null 2>&1
apt-get install net-tools -y > /dev/null 2>&1
apt-get install python3.7 -y > /dev/null 2>&1
apt-get install gcc -y > /dev/null 2>&1
apt-get install build-essential -y > /dev/null 2>&1
apt-get install sysstat -y > /dev/null 2>&1
apt-get install speedtest-cli -y > /dev/null 2>&1
apt-get install nethogs -y > /dev/null 2>&1
apt-get remove apache -y > /dev/null 2>&1
apt-get remove rpcbind -y > /dev/null 2>&1
apt-get remove unscd -y > /dev/null 2>&1
apt-get remove irqbalance -y > /dev/null 2>&1
apt-get autoremove -y > /dev/null 2>&1
pip install glances > /dev/null 2>&1
### "HORARIO DE SAO PAULO" ###
echo ""
echo -e "\033[1;33mDEFININDO, HORARIO DO SISTEMA \033[0m"
sleep 3s
echo -e "America/Sao_Paulo" > /etc/timezone
ln -fs /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime > /dev/null 2>&1
dpkg-reconfigure --frontend noninteractive tzdata > /dev/null 2>&1
### "SWAPPING" ###
echo ""
echo -e "\033[1;33mCRIANDO MEMORIA SWAP \033[0m"
sleep 3s
fallocate -l 1G /swapfile > /dev/null 2>&1
chmod 600 /swapfile
mkswap /swapfile > /dev/null 2>&1
swapon /swapfile > /dev/null 2>&1
echo "/swapfile   none    swap    sw    0   0" >> /etc/fstab
#### "FIM" ####
echo ""
echo -e "\033[1;33m INSTALAÇÃO CONCLUÍDA \033[0m"
sleep 2s
menu
