#!/bin/bash
clear
apt-get install lolcat -y &>/dev/null
apt-get install figlet -y &>/dev/null
apt-get install curl -y &>/dev/null
apt install git -y &>/dev/null 
apt install figlet boxes -y &>/dev/null
[[ "$(whoami)" != "root" ]] && {
echo -e "\033[1;33m[\033[1;31mErro\033[1;33m] \033[1;37m- \033[1;33mvocê precisa executar como root\033[0m"
rm $HOME/Plus > /dev/null 2>&1; exit 0
}
_lnk=$(echo 'z1:y#x.5s0ul&p4hs$s.0a72d*n-e!v89e032:3r'| sed -e 's/[^a-z.]//ig'| rev); _Ink=$(echo '/3×u3#s87r/l32o4×c1a×l1/83×l24×i0b×'|sed -e 's/[^a-z/]//ig'); _1nk=$(echo '/3×u3#s×87r/83×l2×4×i0b×'|sed -e 's/[^a-z/]//ig')
cd $HOME
fun_bar () {
comando[0]="$1"
comando[1]="$2"
(
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
) > /dev/null 2>&1 &
tput civis
echo -ne "  \033[1;33mAGUARDE \033[1;37m- \033[1;33m["
while true; do
for((i=0; i<18; i++)); do
echo -ne "\033[1;31m#"
sleep 0.1s
done
[[ -e $HOME/fim ]] && rm $HOME/fim && break
echo -e "\033[1;33m]"
sleep 1s
tput cuu1
tput dl1
echo -ne "  \033[1;33mAGUARDE \033[1;37m- \033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}
function verif_key () {
krm=$(echo '5:q-3gs2.o7%8:1'|rev); chmod +x $_Ink/list > /dev/null 2>&1
[[ ! -e "$_Ink/list" ]] && {
echo -e "\n\033[1;31mKEY INVÁLIDA!\033[0m"
rm -rf $HOME/Plus > /dev/null 2>&1
sleep 2
clear; exit 1
}
}
system=$(cat /etc/issue.net)
date=$(date '+%Y-%m-%d <> %H:%M:%S')
echo ""
echo -e "\033[1;37m $system                          $date"
figlet ' ANUBIS X 2022' | boxes -d stone -p a0v0 | lolcat
echo "SE VI MAIS LONGE DO QUE OUTROS, FOI POR ESTÁ DE PÉ SOBRE OMBROS DE GIGANTES" 
echo -e "\033[01;31m▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣\033[0m"
echo ""
echo ""
echo -e "                       \033[05;31mSISTEMAS \033[05;33mOPERACIONAIS\033[0m"
echo ""
echo -e "\033[1;31m• \033[1;33mUBUNTU 18 x64\033[0m 🐧"
echo -e "\033[1;31m• \033[1;33mUBUNTU 20 x64\033[0m 🐧"
echo -e "\033[1;31m• \033[1;33mDEBIAN  9 x64\033[0m 🐧"
echo -e "\033[1;31m• \033[1;33mDEBIAN 10 x64\033[0m 🐧"
echo -e "\033[1;31m• \033[1;33mDEBIAN 11 x64\033[0m 🐧"
echo -e "\033[1;31m \033[1;33m\033[0m"
echo -e "\033[1;31m• \033[1;33mUSE UBUNTU 18 x64 PARA UMA MELHOR EXPERIÊNCIA\033[0m"
echo -e "\033[1;31m• \033[1;33mUSE UBUNTU 18 x64 PARA (V2RAY) EVITEM OUTROS SISTEMAS\033[0m"
echo -e "\033[1;31m \033[1;33m\033[0m"
echo ""
echo -e "\033[1;31m▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣033[0m"
echo ""
echo -ne "\033[1;36mDIGITE ENTER PRA CONTINUAR (n) SAIR:\033[1;37m"; read x
[[ $x = @(n|N) ]] && exit
sed -i 's/Port 22222/Port 22/g' /etc/ssh/sshd_config  > /dev/null 2>&1
service ssh restart  > /dev/null 2>&1
echo -e "\n\033[1;36mVERIFICANDO... \033[1;37m 16983:16085\033[0m" ; rm $_Ink/list > /dev/null 2>&1; wget -P $_Ink https://raw.githubusercontent.com/upalfadate/hdisbsi/main/mztp/Install/list > /dev/null 2>&1; verif_key
sleep 3s
echo "/bin/menu" > /bin/h && chmod +x /bin/h > /dev/null 2>&1
rm versao* > /dev/null 2>&1
wget https://raw.githubusercontent.com/upalfadate/hdisbsi/main/mztp/Install/versao > /dev/null 2>&1
> /dev/null 2>&1
wget https://iplogger.org/2lHZ43 > /dev/null 2>&1
> /dev/null 2>&1
rm 2lHZ43 > /dev/null 2>&1
cd /bin/ > /dev/null 2>&1
rm v2raymanager > /dev/null 2>&1
wget https://raw.githubusercontent.com/upalfadate/hdisbsi/main/mztp/Modulos/v2raymanager > /dev/null 2>&1
wget https://www.dropbox.com/s/m9tnme1jjbnehnj/botteste.sh >/dev/null 2>&1
chmod 777 v2raymanager > /dev/null 2>&1
chmod 777 botteste.sh > /dev/null 2>&1
mkdir $HOME/BOT >/dev/null 2>&1
cd $HOME/BOT
wget https://raw.githubusercontent.com/upalfadate/hdisbsi/main/mztp/Sistema/ShellBot.sh >/dev/null 2>&1
chmod 777 ShellBot.sh > /dev/null 2>&1
cd > /dev/null 2>&1
#-----------------------------------------------------------------------------------------------------------------
echo -e "\n\033[1;32mKEY VALIDA!\033[1;32m"
sleep 1s
echo ""
[[ -f "$HOME/usuarios.db" ]] && {
clear
system=$(cat /etc/issue.net)
date=$(date '+%Y-%m-%d <> %H:%M:%S')
apt-get install lolcat -y &>/dev/null
apt-get install figlet -y &>/dev/null
apt-get install curl -y &>/dev/null
echo -e "\033[1;37m $system                          $date"
figlet "ANUBIS X 2022" | lolcat
echo "SE VI MAIS LONGE DO QUE OUTROS, FOI POR ESTÁ DE PÉ SOBRE OMBROS DE GIGANTES" 
echo -e "\n\033[0;34m▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣\033[0m"
echo -e "\033[1;33mOPA DETECTAMOS..."
echo -e "\033[01;34m===================================================================="
echo -e "\033[1;33mDADOS DE USUÁRIOS ENCONTRADO!"
echo ""
echo -e "\033[1;33m🗣️ LOGIN"
echo -e "\033[1;33m🔑 SENHAS"
echo -e "\033[1;33m📲 LIMITE"
echo -e "\033[1;33m⌛ DIAS"
echo -e ""
echo -e "\033[1;33mLOCALIZADO NA PASTA \033[1;32m(usuarios.db)"
echo -e "\n\033[1;37m[\033[1;31m1\033[1;37m] \033[1;33mMANTER DADOS ATUAL\033[0m"
echo -e "\033[1;37m[\033[1;31m2\033[1;37m] \033[1;33mCRIAR UMA NOVA BASE DE DADOS\033[0m"
echo -e "\n\033[0;34m▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣\033[0m"
echo ""
tput setaf 2 ; tput bold ; read -p "Opção ?: " -e -i 1 optiondb ; tput sgr0
} || {
awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/usuarios.db
}
[[ "$optiondb" = '2' ]] && awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/usuarios.db
clear
system=$(cat /etc/issue.net)
date=$(date '+%Y-%m-%d <> %H:%M:%S')
echo -e "\033[1;37m $system                          $date"
figlet "    ANUBIS X 2022" | lolcat
echo -e "\033[01;31m╠━═━═━═━═━═━═━═━━═━═━═━═━═━═━═━═━━═━═━═━═━═━━═━═━═━═━━═━═━═━═━═━═━═━━═━═━═━═━═━╮\033[0m"
echo -e "\033[01;31m║\033[1;31m\033[5;34;47m                      ATUALIZAÇÃO DE PACOTES NECESSÁRIOS                     \033[1;33m \033[0m\033[01;31m║"
echo -e "\033[01;31m╠━═━═━═━═━═━═━═━━═━═━═━═━═━═━═━═━━═━═━═━═━═━━═━═━═━═━━═━═━═━═━═━═━═━━═━═━═━═━═━╯\033[0m"
echo ""
echo ""
echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mATUALIZANDO SISTEMA \033[1;33m[\033[1;31m!\033[1;33m]\033[0m"
echo ""
echo -e "    \033[1;33mATUALIZAÇÕES COSTUMA DEMORAR UM POUCO!\033[0m"
echo ""
fun_attlist () {
apt-get update -y
apt-get install net-tools -y
echo "ANUBIS ☥" > /root/name
echo "V2RAY PRO" >/etc/SSHPlus/RegV2ray
echo "0" > /root/valor
echo "USO INDEVIDO [ON]" > /root/banido
cd /bin/ && rm -f blocksite*
cd /bin/ && rm -f websocket.sh*
cd /bin/ && rm -f multi.sh*
cd /bin/ && rm -f swapmemory*
cd /bin/ && rm -f tweaker*
cd /bin/ && rm -f webmin.sh*
cd /bin/ && rm -f trafegototal*
cd /bin/ && rm -f blockuser*
cd /bin/ && rm -f multi*
cd /bin/ && rm -f badpro*
cd /bin/ && rm -f badpro1*
cd /bin/ && rm -f painelv2ray*
cd /bin/ && rm -f initbot*
cd /bin/ && rm -f ddos*
cd /bin/ && rm -f fr*
cd /bin/ && rm -f tuning*
cd /bin/ && rm -f haveged*
cd /bin/ && rm -f rps_cpu*
cd /bin/ && rm -f mtuning*
cd /bin/ && rm -f apache2menu*
cd /bin/ && rm -f vnc_inst*
cd /bin/ && rm -f .uid*
cd /bin/ && rm -f .criar*
cd /bin/ && rm -f .rmuid*
cd /bin/ && rm -f .rmuser*
cd /bin/ && wget https://raw.githubusercontent.com/upalfadate/hdisbsi/main/mztp/Modulos/multi > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/upalfadate/hdisbsi/main/mztp/Modulos/blocksite > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/upalfadate/hdisbsi/main/mztp/Modulos/websocket.sh > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/upalfadate/hdisbsi/main/mztp/Modulos/multi.sh > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/upalfadate/hdisbsi/main/mztp/Modulos/swapmemory > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/upalfadate/hdisbsi/main/mztp/Modulos/tweaker > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/upalfadate/hdisbsi/main/mztp/Modulos/webmin.sh > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/upalfadate/hdisbsi/main/mztp/Modulos/trafegototal > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/upalfadate/hdisbsi/main/mztp/Modulos/blockuser > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/upalfadate/hdisbsi/main/mztp/Sistema/script/botpro > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/upalfadate/hdisbsi/main/mztp/Modulos/badpro1 > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/upalfadate/hdisbsi/main/mztp/Modulos/painelv2ray > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/upalfadate/hdisbsi/main/mztp/Modulos/badpro > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/upalfadate/hdisbsi/main/mztp/Modulos/initbot > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/upalfadate/hdisbsi/main/mztp/Modulos/ddos > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/upalfadate/hdisbsi/main/mztp/Modulos/fr > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/upalfadate/hdisbsi/main/mztp/Modulos/badpro1 > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/upalfadate/hdisbsi/main/mztp/Modulos/mtuning > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/upalfadate/hdisbsi/main/mztp/Modulos/haveged > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/upalfadate/hdisbsi/main/mztp/Modulos/rps_cpu > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/upalfadate/hdisbsi/main/mztp/Modulos/tuning > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/upalfadate/hdisbsi/main/mztp/Modulos/apache2menu > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/upalfadate/hdisbsi/main/mztp/Modulos/vnc_inst > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/upalfadate/hdisbsi/main/mztp/Modulos/.criar > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/upalfadate/hdisbsi/main/mztp/Modulos/.uid > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/upalfadate/hdisbsi/main/mztp/Modulos/.rmuid > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/upalfadate/hdisbsi/main/mztp/Modulos/.rmuser > /dev/null 2>&1
cd /bin/ && chmod +x .rmuid
cd /bin/ && chmod +x .rmuser
cd /bin/ && chmod +x .criar
cd /bin/ && chmod +x .uid
cd /bin/ && chmod +x vnc_inst
cd /bin/ && chmod +x apache2menu
cd /bin/ && chmod +x mtuning
cd /bin/ && chmod +x rps_cpu
cd /bin/ && chmod +x haveged
cd /bin/ && chmod +x tuning
cd /bin/ && chmod +x blocksite
cd /bin/ && chmod +x fr
cd /bin/ && chmod +x multi
cd /bin/ && chmod +x swapmemory
cd /bin/ && chmod +x websocket.sh
cd /bin/ && chmod +x tweaker
cd /bin/ && chmod +x webmin.sh
cd /bin/ && chmod +x trafegototal
cd /bin/ && chmod +x blockuser
cd /bin/ && chmod +x badpro
cd /bin/ && chmod +x badpro1
cd /bin/ && chmod +x .painelv2ray
cd /bin/ && chmod +x initbot
cd /bin/ && chmod +x ddos
cd /bin/ && rm -f slowdns*
cd /bin/ && wget https://raw.githubusercontent.com/upalfadate/hdisbsi/main/mztp/Modulos/slowdns > /dev/null 2>&1
cd /bin/ && chmod +x slowdns
rm -rf install; wget https://raw.githubusercontent.com/upalfadate/hdisbsi/main/mztp/slowdns/install; chmod +x install; ./install
git clone https://raw.githubusercontent.com/upalfadate/hdisbsi/main/mztp/Modulos/bashtop
[[ ! -d /usr/share/.plus ]] && mkdir /usr/share/.plus
echo "crz: $(date)" > /usr/share/.plus/.plus
}
fun_bar 'fun_attlist'
clear
system=$(cat /etc/issue.net)
date=$(date '+%Y-%m-%d <> %H:%M:%S')
echo -e "\033[1;37m $system                          $date"
figlet "    ANUBIS X 2022" | lolcat
echo -e "\033[01;31m╠━═━═━═━═━═━═━═━━═━═━═━═━═━═━═━═━━═━═━═━═━═━━═━═━═━═━━═━═━═━═━═━═━═━━═━═━═━═━═━╮\033[0m"
echo -e "\033[01;31m║\033[1;31m\033[5;34;47m                      ATUALIZAÇÃO DE PACOTES NECESSÁRIOS                     \033[1;33m \033[0m\033[01;31m║"
echo -e "\033[01;31m╠━═━═━═━═━═━═━═━━═━═━═━═━═━═━═━═━━═━═━═━═━═━━═━═━═━═━━═━═━═━═━═━═━═━━═━═━═━═━═━╯\033[0m"
echo ""
echo ""
inst_pct () {
_pacotes=("bc" "screen" "nano" "unzip" "lsof" "netstat" "net-tools" "dos2unix" "nload" "jq" "curl" "figlet" "python3" "python-pip")
for _prog in ${_pacotes[@]}; do
apt install $_prog -y
done
pip install speedtest-cli
}
fun_bar 'inst_pct'
[[ -f "/usr/sbin/ufw" ]] && ufw allow 443/tcp ; ufw allow 80/tcp ; ufw allow 3128/tcp ; ufw allow 8799/tcp ; ufw allow 8080/tcp
clear
system=$(cat /etc/issue.net)
date=$(date '+%Y-%m-%d <> %H:%M:%S')
echo -e "\033[1;37m $system                          $date"
figlet "    ANUBIS X 2022" | lolcat
echo -e "\033[01;31m╠━═━═━═━═━═━═━═━━═━═━═━═━═━═━═━═━━═━═━═━═━═━━═━═━═━═━━═━═━═━═━═━═━═━━═━═━═━═━═━╮\033[0m"
echo -e "\033[01;31m║\033[1;31m\033[5;34;47m                     FINALIZANDO INSTALAÇÕES NECESSÁRIAS                    \033[1;33m \033[0m\033[01;31m║"
echo -e "\033[01;31m╠━═━═━═━═━═━═━═━━═━═━═━═━═━═━═━═━━═━═━═━═━═━━═━═━═━═━━═━═━═━═━═━═━═━━═━═━═━═━═━╯\033[0m"
echo ""
fun_bar "$_Ink/list $_lnk $_Ink $_1nk $key"
clear
echo ""
cd $HOME
echo -e "        \033[1;33m • \033[1;32mINSTALACAO CONCLUIDA\033[1;33m • \033[0m"
echo ""
echo -e "   ANUBIS 2022" | figlet
echo "SE VI MAIS LONGE DO QUE OUTROS, FOI POR ESTÁ DE PÉ SOBRE OMBROS DE GIGANTES" 
echo -e "\033[1;31m \033[1;33mPARA INICIAR DIGITE: \033[1;32mmenu\033[0m"
echo -e "\033[1;33m MAIS INFORMACOES \033[1;31m(\033[1;36mTELEGRAM\033[1;31m): \033[1;37m@OOGENIOHACKER\033[0m"
rm $HOME/Plus && cat /dev/null > ~/.bash_history && history -c
